services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-api
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "127.0.0.1:8000:8000"

    networks:
      - nextcloud

networks:
  nextcloud:
    external: true
    name: nextcloud_default
